### ISSUE TITLE
Hi, I'm trying to compile your project but there're 2 errors: glicko2-csharp and config-secret.json are not found. Can you help me?

### ISSUE THREAD

**Issue by robisoft** [Chess-Variants-Training/Chess-Variants-Training#9]

**Comment by ProgramFOX** [comment]
Hey! Sorry for the late reply, I wasn't home.

For glicko2-csharp, you have to create a local NuGet package for https://github.com/MaartenStaa/glicko2-csharp
(It's been a long time since I did that myself, so I can't give further detailed steps without trying it all over again).

config.secret.json looks like this (certain fields are redacted, you'll have to fill them in again for yourself):
```
{
  "Email": {
    "RequireEmailVerification": true,
    "SmtpHost": "smtp.gmail.com",
    "SmtpPort": 587,
    "SmtpUsername": "",
    "Password": "",
    "SenderName": "",
    "FromAddress": ""
  },
  "RecaptchaKey": ""
}
```
**Note**: setting RequireEmailVerification to false will NOT disable email verification at this point (I forgot to actually use that setting, it seems. Should fix. Won't do this immediately because travel. You'll have to fill in the actual email settings to get account creation to work) (Also recaptcha isn't optional yet. It's a bit... under-configurable at this moment, let's say. Fetch your own key and adjust https://github.com/Chess-Variants-Training/Chess-Variants-Training/blob/0738eafa5dc079600a5ae65621cdb0ed28c68954/src/ChessVariantsTraining/Views/User/Register.cshtml#L16 because otherwise that won't work either. Or you can go into UserController and make it optional).

Sorry for that trouble; I have created #10 to track these things, because configuration for local dev builds should definitely be made easier.

**Comment by ProgramFOX** [comment]
I do want to note that the email configuration and recaptcha config are not required if you do not intend to create a user account. If you do, you can't avoid it unless you edit the code.

**Comment by ProgramFOX** [comment]
Setting RequireEmailVerification to false is now respected.

Setting RecaptchaKey to an empty string will still cause the captcha to show up on the register page, but the server code won't check it anymore.
